# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-08 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('data_source', enumfields.fields.EnumIntegerField(default=1, enum=events.models.DataSources, verbose_name='Event data source')),
                ('facebook_page_id', models.CharField(default='1415745085336451', max_length=200)),
                ('linkedevents_params', models.CharField(default='?keyword=yso:p8692', max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
