# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-04 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digi', '0002_theme_page_add_body_and_blog_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='ProjectPage',
        ),
    ]
