# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-30 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi', '0006_projectrole_themerole'),
    ]

    operations = [
        migrations.AddField(
            model_name='themepage',
            name='type',
            field=models.CharField(default='Teema', max_length=10),
        ),
    ]
