# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-24 13:05
from __future__ import unicode_literals

import digihel.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
        ('digi', '0008_auto_20160909_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideFrontPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=(digihel.mixins.RelativeURLMixin, 'wagtailcore.page'),
        ),
    ]
