# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-23 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi', '0011_fix_guidepages_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='illustration_filename',
            field=models.CharField(default='hki-tietoaineisto.svg', max_length=100),
        ),
        migrations.AddField(
            model_name='indicator',
            name='source_description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
