# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-23 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi', '0012_added_fields_to_indicators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='illustration_filename',
            field=models.CharField(default='images/hki-tietoaineisto.svg', max_length=100),
        ),
    ]
