# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-24 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi', '0012_themepage_twitter_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='illustration_filename',
            field=models.CharField(default='images/hki-tietoaineisto.svg', max_length=100),
        ),
        migrations.AddField(
            model_name='indicator',
            name='slug',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='indicator',
            name='source_description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='indicator',
            name='source_url',
            field=models.CharField(default='http://dev.hel.fi/apis', max_length=100),
        ),
    ]
