# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-23 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi', '0013_fix_default_in_indicator_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='source_url',
            field=models.CharField(default='http://dev.hel.fi/apis', max_length=100),
        ),
    ]
