# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-15 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi', '0013_add_KPI_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='phase',
            field=models.CharField(choices=[('', 'No phase'), ('DI', 'Selvitys'), ('AL', 'Alfa'), ('BE', 'Beta'), ('LI', 'Tuotanto'), ('RE', 'Poisto')], default='', max_length=2),
        ),
    ]
