# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-21 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi', '0015_auto_20170419_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='phase',
            field=models.CharField(blank=True, choices=[('', 'No phase'), ('DI', 'Selvitys'), ('AL', 'Alfa'), ('BE', 'Beta'), ('LI', 'Tuotanto'), ('RE', 'Poisto')], default='', max_length=2, null=True),
        ),
    ]
