# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-08-10 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0013_make_rendition_upload_callable'),
        ('digi', '0017_projectpage_twitter_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontpage',
            name='hero_background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='themepage',
            name='promote_on_front_page',
            field=models.BooleanField(default=False, help_text='Show summary on front page'),
        ),
    ]
