# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-14 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi', '0018_auto_20170810_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontpage',
            name='banners_header',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Banner header'),
        ),
        migrations.AddField(
            model_name='frontpage',
            name='news_header',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='News header'),
        ),
        migrations.AddField(
            model_name='frontpage',
            name='themes_header',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Themes header'),
        ),
    ]
