# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-23 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0039_collectionviewrestriction'),
        ('digi', '0018_auto_20170810_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontpage',
            name='news_index_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
