# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-14 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi', '0019_add_header_fields_to_frontpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(default='', max_length=100, verbose_name='Header')),
                ('text', models.CharField(max_length=255, verbose_name='Text')),
                ('link_text', models.CharField(max_length=50, verbose_name='Link text')),
                ('link_url', models.CharField(default='', max_length=100, verbose_name='Link URL')),
                ('icon_file', models.FileField(upload_to='', verbose_name='Icon file')),
                ('icon_alt_text', models.CharField(default='', max_length=100, verbose_name='Icon alt text')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['order'],
            },
        ),
    ]
