# Generated by Django 2.2.1 on 2019-10-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi', '0021_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontpage',
            name='projects_header',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Projects header'),
        ),
    ]
