# Generated by Django 2.2.1 on 2019-10-23 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi', '0022_frontpage_projects_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='themeindexpage',
            name='guides_and_support_header',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Guides and support header'),
        ),
    ]
