# Generated by Django 2.2.1 on 2019-10-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi', '0023_themeindexpage_guides_and_support_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='phase',
            field=models.CharField(blank=True, choices=[('', 'No phase'), ('PR', 'Valmistelu'), ('EX', 'Kokeilu'), ('EN', 'Käytössä')], default='', max_length=2, null=True),
        ),
    ]
