# Generated by Django 2.2.1 on 2019-11-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi', '0024_change_phases'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontpage',
            name='hero_badge_text',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Hero badge text'),
        ),
        migrations.AddField(
            model_name='frontpage',
            name='hero_badge_url',
            field=models.URLField(blank=True, default='', max_length=300, null=True, verbose_name='Hero badge link'),
        ),
    ]
