# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-25 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kehmet', '0004_add_page_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='kehmetcontentpage',
            name='show_in_submenus',
            field=models.BooleanField(default=True, help_text='Page is visible on the submenu', verbose_name='Show in sub menus'),
        ),
    ]
