# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 17:02
from __future__ import unicode_literals

from django.db import migrations
import wagtail.contrib.table_block.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks
import wagtail_svgmap.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('kehmet', '0005_kehmetcontentpage_show_in_submenus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kehmetcontentpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock()), ('image_map', wagtail.wagtailcore.blocks.StructBlock((('map', wagtail_svgmap.blocks._ImageMapChoiceBlock(label='Image map', required=True)), ('css_class', wagtail.wagtailcore.blocks.CharBlock(label='CSS class', required=False))))), ('two_columns', wagtail.wagtailcore.blocks.StructBlock((('left_column', wagtail.wagtailcore.blocks.StreamBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock()), ('image_map', wagtail.wagtailcore.blocks.StructBlock((('map', wagtail_svgmap.blocks._ImageMapChoiceBlock(label='Image map', required=True)), ('css_class', wagtail.wagtailcore.blocks.CharBlock(label='CSS class', required=False)))))), icon='arrow-left', label='Left column content')), ('right_column', wagtail.wagtailcore.blocks.StreamBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock()), ('image_map', wagtail.wagtailcore.blocks.StructBlock((('map', wagtail_svgmap.blocks._ImageMapChoiceBlock(label='Image map', required=True)), ('css_class', wagtail.wagtailcore.blocks.CharBlock(label='CSS class', required=False)))))), icon='arrow-right', label='Right column content'))))), ('collapsible', wagtail.wagtailcore.blocks.RichTextBlock(icon='collapse-down', label='Collapsible paragraph', template='content/blocks/collapsible.html')))),
        ),
        migrations.AlterField(
            model_name='kehmetfrontpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock()), ('image_map', wagtail.wagtailcore.blocks.StructBlock((('map', wagtail_svgmap.blocks._ImageMapChoiceBlock(label='Image map', required=True)), ('css_class', wagtail.wagtailcore.blocks.CharBlock(label='CSS class', required=False))))), ('two_columns', wagtail.wagtailcore.blocks.StructBlock((('left_column', wagtail.wagtailcore.blocks.StreamBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock()), ('image_map', wagtail.wagtailcore.blocks.StructBlock((('map', wagtail_svgmap.blocks._ImageMapChoiceBlock(label='Image map', required=True)), ('css_class', wagtail.wagtailcore.blocks.CharBlock(label='CSS class', required=False)))))), icon='arrow-left', label='Left column content')), ('right_column', wagtail.wagtailcore.blocks.StreamBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock()), ('image_map', wagtail.wagtailcore.blocks.StructBlock((('map', wagtail_svgmap.blocks._ImageMapChoiceBlock(label='Image map', required=True)), ('css_class', wagtail.wagtailcore.blocks.CharBlock(label='CSS class', required=False)))))), icon='arrow-right', label='Right column content'))))), ('collapsible', wagtail.wagtailcore.blocks.RichTextBlock(icon='collapse-down', label='Collapsible paragraph', template='content/blocks/collapsible.html')))),
        ),
    ]
