# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-26 10:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL of the page where the user was')),
                ('user_agent', models.CharField(blank=True, max_length=400, null=True, verbose_name="The user agent string of the user's browser")),
                ('subject', models.TextField(blank=True, null=True, verbose_name='Subject')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('body', models.TextField(verbose_name='Body')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Notifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('slack', 'Slack')], max_length=20)),
                ('url_base', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SlackNotifier',
            fields=[
                ('notifier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feedback.Notifier')),
                ('webhook_url', models.URLField()),
                ('channel', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('icon_emoji', models.CharField(blank=True, max_length=50, null=True)),
            ],
            bases=('feedback.notifier',),
        ),
    ]
