# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-26 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='slacknotifier',
            name='icon_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
