# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-02 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'term categories',
                'verbose_name': 'term category',
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('mtime', models.DateTimeField(auto_now=True, verbose_name='last modified on')),
                ('name', models.CharField(max_length=128)),
                ('body', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('list_visible', models.BooleanField(db_index=True, default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='glossy.Category')),
            ],
        ),
    ]
