# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-20 12:35
from __future__ import unicode_literals

import digihel.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
        ('glossy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='glossy.Category')),
            ],
            options={
                'abstract': False,
            },
            bases=(digihel.mixins.RelativeURLMixin, 'wagtailcore.page'),
        ),
    ]
