# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-15 12:37
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20160913_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='personindexpage',
            name='body',
            field=wagtail.core.fields.RichTextField(default=''),
        ),
    ]
