# Generated by Django 2.2.1 on 2019-11-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_add_collapsible_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedcontentpage',
            name='contact_information_header',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Contact information header'),
        ),
        migrations.AddField(
            model_name='linkedcontentpage',
            name='links_header',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Links header'),
        ),
    ]
