# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-16 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_language_versions'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='show_sidebar_events',
            field=models.BooleanField(default=False, verbose_name='show sidebar events'),
        ),
        migrations.AddField(
            model_name='linkedcontentpage',
            name='show_sidebar_events',
            field=models.BooleanField(default=False, verbose_name='show sidebar events'),
        ),
    ]
