# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('wagtailimages', '0019_delete_filter'),
        ('wagtailcore', '0039_collectionviewrestriction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('abstract', models.TextField(verbose_name='abstract')),
                ('content', wagtail.wagtailcore.fields.RichTextField(verbose_name='content')),
                ('school', models.CharField(blank=True, max_length=128, verbose_name='school')),
                ('student_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='student count')),
                ('case_type', models.CharField(blank=True, max_length=256, verbose_name='type')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CaseKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='helsinkioppii.Case')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helsinkioppii_casekeyword_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, max_length=128, verbose_name='school grade')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=128, verbose_name='school subject')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='helsinkioppii.SchoolGrade', verbose_name='school grade'),
        ),
        migrations.AddField(
            model_name='case',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='case',
            name='keywords',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='helsinkioppii.CaseKeyword', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='case',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='helsinkioppii.SchoolSubject', verbose_name='school subject'),
        ),
    ]
