# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0039_collectionviewrestriction'),
        ('wagtailimages', '0019_delete_filter'),
        ('helsinkioppii', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelsinkiOppiiIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('hero_title', models.CharField(blank=True, max_length=256, verbose_name='lift title')),
                ('case_lifts', wagtail.wagtailcore.fields.StreamField((('case', wagtail.wagtailcore.blocks.StructBlock((('icon', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('icon-signpost', 'signpost'), ('icon-lifering', 'lifering'), ('icon-info', 'info')])), ('case', wagtail.wagtailcore.blocks.PageChooserBlock(target_model=['helsinkioppii.Case']))))),), blank=True)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='hero image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
