# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 10:05
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('helsinkioppii', '0003_case_list_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helsinkioppiiindexpage',
            name='case_lifts',
            field=wagtail.wagtailcore.fields.StreamField((('case', wagtail.wagtailcore.blocks.StructBlock((('case', wagtail.wagtailcore.blocks.PageChooserBlock(target_model=['helsinkioppii.Case'])),))),), blank=True),
        ),
    ]
