# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('helsinkioppii', '0005_banner_lifts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helsinkioppiiindexpage',
            name='hero_title',
        ),
        migrations.AddField(
            model_name='helsinkioppiiindexpage',
            name='banner_section_description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='banner section description'),
        ),
        migrations.AddField(
            model_name='helsinkioppiiindexpage',
            name='banner_section_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='banner section title'),
        ),
        migrations.AddField(
            model_name='helsinkioppiiindexpage',
            name='case_section_description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='case section description'),
        ),
        migrations.AddField(
            model_name='helsinkioppiiindexpage',
            name='case_section_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='case section title'),
        ),
        migrations.AddField(
            model_name='helsinkioppiiindexpage',
            name='hero_content',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='hero content'),
        ),
        migrations.AddField(
            model_name='helsinkioppiiindexpage',
            name='social_section_description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='social section description'),
        ),
        migrations.AddField(
            model_name='helsinkioppiiindexpage',
            name='social_section_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='social section title'),
        ),
    ]
