# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('wagtailcore', '0039_collectionviewrestriction'),
        ('helsinkioppii', '0006_section_content_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('hero_content', wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='hero content')),
                ('training_section_title', models.CharField(blank=True, max_length=255, verbose_name='training section title')),
                ('training_section_description', wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='training section description')),
                ('training_lifts', wagtail.wagtailcore.fields.StreamField((('training', wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock(max_length=120, required=True)), ('time', wagtail.wagtailcore.blocks.DateTimeBlock(required=False)), ('description', wagtail.wagtailcore.blocks.TextBlock(required=False)), ('link', wagtail.wagtailcore.blocks.URLBlock(required=True))))),), blank=True)),
                ('banner_section_title', models.CharField(blank=True, max_length=255, verbose_name='banner section title')),
                ('banner_section_description', wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='banner section description')),
                ('banner_lifts', wagtail.wagtailcore.fields.StreamField((('banner', wagtail.wagtailcore.blocks.StructBlock((('icon', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False)), ('title', wagtail.wagtailcore.blocks.CharBlock(max_length=120)), ('abstract', wagtail.wagtailcore.blocks.TextBlock(max_length=225)), ('page', wagtail.wagtailcore.blocks.PageChooserBlock())))),), blank=True)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='hero image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
