# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_personindexpage_body'),
        ('helsinkioppii', '0007_training_index_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('case', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='helsinkioppii.Case')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='people.Person')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
    ]
