# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helsinkioppii', '0008_case_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(blank=True, max_length=128, verbose_name='theme')),
            ],
        ),
        migrations.RemoveField(
            model_name='case',
            name='case_type',
        ),
        migrations.AddField(
            model_name='case',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='helsinkioppii.CaseTheme', verbose_name='theme'),
        ),
    ]
