# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 07:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helsinkioppii', '0010_alter_banner_lift_block'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casetheme',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='schoolgrade',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='schoolsubject',
            options={'ordering': ['pk']},
        ),
    ]
