# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 09:28
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('helsinkioppii', '0011_snippet_default_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='content_cons',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='Cons'),
        ),
        migrations.AddField(
            model_name='case',
            name='content_evaluation',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='How the learning was evaluated'),
        ),
        migrations.AddField(
            model_name='case',
            name='content_how',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='How it was done'),
        ),
        migrations.AddField(
            model_name='case',
            name='content_materials',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='What materials were useed'),
        ),
        migrations.AddField(
            model_name='case',
            name='content_objectives',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='Objectives'),
        ),
        migrations.AddField(
            model_name='case',
            name='content_pros',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='Pros'),
        ),
        migrations.AddField(
            model_name='case',
            name='content_what',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='What was done'),
        ),
        migrations.AddField(
            model_name='case',
            name='content_who',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='Who participated'),
        ),
        migrations.AlterField(
            model_name='case',
            name='content',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='content'),
        ),
    ]
