# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-12 11:42
from __future__ import unicode_literals

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('helsinkioppii', '0012_change_case_content_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='grades',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='_case_grades_+', to='helsinkioppii.SchoolGrade', verbose_name='school grades'),
        ),
        migrations.AddField(
            model_name='case',
            name='subjects',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='_case_subjects_+', to='helsinkioppii.SchoolSubject', verbose_name='school subjects'),
        ),
        migrations.AddField(
            model_name='case',
            name='themes',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='_case_themes_+', to='helsinkioppii.CaseTheme', verbose_name='themes'),
        ),
    ]
