# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-27 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helsinkioppii', '0013_many_to_many_relationships'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='cc_license',
            field=models.BooleanField(default=False, help_text='I am licensing this content under Creative Commons license.', verbose_name='Creative Commons license'),
        ),
        migrations.AddField(
            model_name='case',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='draft'),
        ),
        migrations.AddField(
            model_name='case',
            name='photo_permission',
            field=models.BooleanField(default=False, help_text='I have the permission to publish the images associated to this case. I have the permission to use the images or I have the copyright to the images. People have given permission to publish the images they appear in.', verbose_name='Photo permission'),
        ),
    ]
