# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-27 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helsinkioppii', '0014_case_legal_and_draft_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='draft',
            field=models.BooleanField(default=False, help_text='Hidden draft flag used with frontend editing.', verbose_name='draft'),
        ),
    ]
