# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-07 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('wagtaildocs', '0007_merge'),
        ('helsinkioppii', '0015_alter_case_admin_panel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField(help_text='One of the five document slots the attachment takes up from a Case.', verbose_name='Attachment ordinal')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='helsinkioppii.Case', verbose_name='Case')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.Document', verbose_name='file')),
            ],
            options={
                'ordering': ['slot'],
            },
        ),
        migrations.CreateModel(
            name='CaseGalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField(help_text='One of the eight gallery image slots the images takes up from a Case.', verbose_name='Gallery image ordinal')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='helsinkioppii.Case', verbose_name='Case')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image', verbose_name='Image')),
            ],
            options={
                'ordering': ['slot'],
            },
        ),
        migrations.CreateModel(
            name='CaseSidebarLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=512, verbose_name='Link URL')),
                ('text', models.CharField(max_length=256, verbose_name='Link text')),
                ('slot', models.PositiveSmallIntegerField(help_text='One of the five link slots the link takes up from a Case.', verbose_name='Link ordinal')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sidebar_links', to='helsinkioppii.Case', verbose_name='Case')),
            ],
            options={
                'ordering': ['slot'],
            },
        ),
    ]
