# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-12 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('helsinkioppii', '0016_case_attachments_gallery_images_and_sidebar_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='caselistpage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='hero image'),
        ),
        migrations.AddField(
            model_name='caselistpage',
            name='lead_text',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='lead text'),
        ),
    ]
