# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-19 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helsinkioppii', '0017_case_list_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='helsinkioppiiindexpage',
            name='youtube_embed',
            field=models.URLField(blank=True, max_length=255, verbose_name='Youtube video embed'),
        ),
    ]
