# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-20 05:46
from __future__ import unicode_literals

from django.db import migrations
import enumfields.fields
import helsinkioppii.models.cases


class Migration(migrations.Migration):

    dependencies = [
        ('helsinkioppii', '0022_i18n_alterations'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolgrade',
            name='color',
            field=enumfields.fields.EnumField(default='orange', enum=helsinkioppii.models.cases.SchoolGradeColors, help_text='Color associated with the level of education.', max_length=32),
            preserve_default=False,
        ),
    ]
